#!/bin/bash

# Use of this file is at your own risk.

# Variable
rootCert="/path/to/cert"
intermediateCert'"/path/to/cert"
keyChain="/Library/Keychains/System.keychain"

# Add Cert(s) to System Certificate Store
# If cert is a Root Cert
if [ "$rootCert" != "" ]; then
	security add-trusted-cert -d -r trustRoot -k "$keyChain" "$rootCert"
fi

# If cert is an intermediate certificate
if [ "$intermediateCert" != "" ]; then
	security add-trusted-cert -d -r trustAsRoot -k "$keyChain" "$intermediateCert"
fi